[package]
name = "ocae"
version = "2.0.0"
authors = ["Chyler Morrison <contact@chyler.info>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1"
petgraph = "0.5"
riff = "0.1"
rand = "0.7"
wav = "0.1"
